words_by_kana = {
    "あ": [("あさ", "Morning"), ("あめ", "Rain"), ("あか", "Red"), ("あし", "Foot"), ("あと", "After"), ("あき", "Autumn"), ("あに", "Older brother"), ("あね", "Older sister"), ("あそこ", "Over there"), ("あした", "Tomorrow")],
    "い": [("いえ", "House"), ("いぬ", "Dog"), ("いま", "Now"), ("いす", "Chair"), ("いと", "Thread"), ("いけ", "Pond"), ("いろ", "Color"), ("いみ", "Meaning"), ("いち", "One"), ("いしゃ", "Doctor")],
    "う": [("うみ", "Sea"), ("うた", "Song"), ("うし", "Cow"), ("うで", "Arm"), ("うわさ", "Rumor"), ("うま", "Horse"), ("うち", "Home"), ("うどん", "Udon"), ("うんどう", "Exercise"), ("うれしい", "Happy")],
    "え": [("えき", "Station"), ("えんぴつ", "Pencil"), ("えがお", "Smile"), ("えいが", "Movie"), ("えだ", "Branch"), ("えほん", "Picture book"), ("えび", "Shrimp"), ("えらぶ", "Choose"), ("えんそく", "Excursion"), ("えいご", "English language")],
    "お": [("おちゃ", "Tea"), ("おかし", "Sweets"), ("おんがく", "Music"), ("おかね", "Money"), ("おとこ", "Man"), ("おんな", "Woman"), ("おふろ", "Bath"), ("おおきい", "Big"), ("おそい", "Late/slow"), ("およぐ", "Swim")],
    "か": [("かさ", "Umbrella"), ("かみ", "Paper"), ("かばん", "Bag"), ("かぜ", "Cold (illness)"), ("かお", "Face"), ("かぎ", "Key"), ("かた", "Shoulder"), ("かど", "Corner"), ("かえる", "Frog"), ("かいもの", "Shopping")],
    "き": [("き", "Tree"), ("きた", "North"), ("きっぷ", "Ticket"), ("きもの", "Kimono"), ("きせつ", "Season"), ("きょう", "Today"), ("きれい", "Beautiful/clean"), ("きぼう", "Hope"), ("きのこ", "Mushroom"), ("きゅうり", "Cucumber")],
    "く": [("くち", "Mouth"), ("くるま", "Car"), ("くつ", "Shoes"), ("くも", "Cloud"), ("くに", "Country"), ("くすり", "Medicine"), ("くじら", "Whale"), ("くだもの", "Fruit"), ("くうこう", "Airport"), ("くらす", "Class")],
    "け": [("けさ", "This morning"), ("けしき", "Scenery"), ("けいたい", "Mobile phone"), ("けが", "Injury"), ("けむり", "Smoke"), ("けんか", "Fight"), ("けんこう", "Health"), ("けいかく", "Plan"), ("けーき", "Cake"), ("けんきゅう", "Research")],
    "こ": [("こども", "Child"), ("ことば", "Word/language"), ("こころ", "Heart/mind"), ("こえ", "Voice"), ("こめ", "Rice"), ("こたえ", "Answer"), ("こおり", "Ice"), ("こうえん", "Park"), ("こうちゃ", "Black tea"), ("こしょう", "Pepper")],
    "さ": [("さかな", "Fish"), ("さくら", "Cherry blossom"), ("さとう", "Sugar"), ("さむい", "Cold (weather)"), ("さる", "Monkey"), ("さいふ", "Wallet"), ("さしみ", "Sashimi"), ("さんぽ", "Walk"), ("さつえい", "Filming"), ("さようなら", "Goodbye")],
    "し": [("しごと", "Work"), ("しろ", "White/castle"), ("しお", "Salt"), ("しか", "Deer"), ("しんぶん", "Newspaper"), ("しつもん", "Question"), ("しっぱい", "Failure"), ("しあわせ", "Happiness"), ("しゅみ", "Hobby"), ("しゅくだい", "Homework")],
    "す": [("すし", "Sushi"), ("すいか", "Watermelon"), ("すこし", "A little"), ("すぐ", "Immediately"), ("すずしい", "Cool"), ("すばらしい", "Wonderful"), ("すいようび", "Wednesday"), ("すもう", "Sumo"), ("すな", "Sand"), ("すべる", "Slide/slip")],
    "せ": [("せかい", "World"), ("せんせい", "Teacher"), ("せんたく", "Laundry"), ("せっけん", "Soap"), ("せいかつ", "Daily life"), ("せなか", "Back"), ("せりふ", "Line/dialogue"), ("せいと", "Student"), ("せみ", "Cicada"), ("せつめい", "Explanation")],
    "そ": [("そら", "Sky"), ("そと", "Outside"), ("そば", "Soba"), ("そふぁ", "Sofa"), ("そうじ", "Cleaning"), ("そうだん", "Consultation"), ("そつぎょう", "Graduation"), ("そんけい", "Respect"), ("それ", "That"), ("そくど", "Speed")],
    "た": [("たまご", "Egg"), ("たべる", "Eat"), ("たのしい", "Fun"), ("たかい", "High/expensive"), ("たび", "Trip"), ("たいふう", "Typhoon"), ("たくさん", "Many"), ("たてもの", "Building"), ("たんじょうび", "Birthday"), ("たすける", "Help/save")],
    "ち": [("ちず", "Map"), ("ちいさい", "Small"), ("ちから", "Power"), ("ちゅうごく", "China"), ("ちょうしょく", "Breakfast"), ("ちかてつ", "Subway"), ("ちーず", "Cheese"), ("ちほう", "Region"), ("ちけっと", "Ticket"), ("ちょっと", "A bit")],
    "つ": [("つき", "Moon"), ("つくえ", "Desk"), ("つめたい", "Cold (to touch)"), ("つよい", "Strong"), ("つり", "Fishing"), ("つうがく", "School commute"), ("つづく", "Continue"), ("つかう", "Use"), ("つまらない", "Boring"), ("つける", "Attach/turn on")],
    "て": [("て", "Hand"), ("てがみ", "Letter"), ("てんき", "Weather"), ("てら", "Temple"), ("てつだう", "Help"), ("てーぶる", "Table"), ("ていねい", "Polite"), ("てんぷら", "Tempura"), ("てんらんかい", "Exhibition"), ("てじな", "Magic trick")],
    "と": [("とけい", "Clock"), ("ともだち", "Friend"), ("とり", "Bird"), ("としょかん", "Library"), ("とおい", "Far"), ("とおか", "Tenth day"), ("とびら", "Door"), ("とまる", "Stop/stay"), ("とくい", "Good at"), ("とまと", "Tomato")],
    "な": [("なつ", "Summer"), ("なまえ", "Name"), ("なに", "What"), ("なか", "Inside/middle"), ("なみだ", "Tears"), ("ならう", "Learn"), ("なれる", "Get used to"), ("なす", "Eggplant"), ("なべ", "Pot/hotpot"), ("なぞ", "Riddle")],
    "に": [("にく", "Meat"), ("にほん", "Japan"), ("にわ", "Garden"), ("にぎやか", "Lively"), ("にんじん", "Carrot"), ("にゅうがく", "School admission"), ("にちようび", "Sunday"), ("にげる", "Run away"), ("におい", "Smell"), ("にほんご", "Japanese language")],
    "ぬ": [("ぬの", "Cloth"), ("ぬるい", "Lukewarm"), ("ぬぐ", "Take off/wipe"), ("ぬれる", "Get wet"), ("ぬすむ", "Steal"), ("ぬま", "Swamp"), ("ぬいぐるみ", "Stuffed toy"), ("ぬか", "Rice bran"), ("ぬりえ", "Coloring book"), ("ぬくもり", "Warmth")],
    "ね": [("ねこ", "Cat"), ("ねつ", "Fever"), ("ねる", "Sleep"), ("ねだん", "Price"), ("ねぎ", "Green onion"), ("ねんど", "Clay/year level"), ("ねがう", "Wish"), ("ねずみ", "Mouse"), ("ねっしん", "Enthusiastic"), ("ねっと", "Internet/net")],
    "の": [("のみもの", "Drink"), ("のり", "Seaweed"), ("のど", "Throat"), ("のこる", "Remain"), ("のぼる", "Climb"), ("のうりょく", "Ability"), ("のーと", "Notebook"), ("のどか", "Peaceful"), ("のぞむ", "Desire"), ("のうか", "Farmer")],
    "は": [("はな", "Flower"), ("はし", "Bridge/chopsticks"), ("はる", "Spring"), ("はは", "Mother"), ("はやい", "Fast/early"), ("はこ", "Box"), ("はくぶつかん", "Museum"), ("はたらく", "Work"), ("はなす", "Speak"), ("はじめる", "Begin")],
    "ひ": [("ひと", "Person"), ("ひる", "Noon"), ("ひこうき", "Airplane"), ("ひだり", "Left"), ("ひかり", "Light"), ("ひみつ", "Secret"), ("ひっこし", "Move (house)"), ("ひつよう", "Necessary"), ("ひま", "Free time"), ("ひらがな", "Hiragana")],
    "ふ": [("ふね", "Ship"), ("ふゆ", "Winter"), ("ふく", "Clothes"), ("ふで", "Brush/pen"), ("ふるい", "Old"), ("ふつう", "Normal"), ("ふしぎ", "Mysterious"), ("ふろ", "Bath"), ("ふうせん", "Balloon"), ("ふるさと", "Hometown")],
    "へ": [("へや", "Room"), ("へんじ", "Reply"), ("へた", "Unskilled"), ("へいわ", "Peace"), ("へん", "Strange/area"), ("へる", "Decrease"), ("へんこう", "Change"), ("へいき", "Weapon/calm"), ("へび", "Snake"), ("へんしゅう", "Editing")],
    "ほ": [("ほん", "Book"), ("ほし", "Star"), ("ほうちょう", "Kitchen knife"), ("ほっと", "Hot"), ("ほか", "Other"), ("ほうそう", "Broadcast"), ("ほけん", "Insurance"), ("ほしい", "Want"), ("ほめる", "Praise"), ("ほっぺ", "Cheek")],
    "ま": [("まど", "Window"), ("まいにち", "Every day"), ("まえ", "Front/before"), ("まち", "Town"), ("まつり", "Festival"), ("まくら", "Pillow"), ("まほう", "Magic"), ("まじめ", "Serious"), ("まんが", "Manga"), ("まなぶ", "Learn")],
    "み": [("みず", "Water"), ("みせ", "Shop"), ("みぎ", "Right"), ("みどり", "Green"), ("みらい", "Future"), ("みかん", "Mandarin orange"), ("みつける", "Find"), ("みんぞく", "Ethnic group"), ("みそ", "Miso"), ("みじかい", "Short")],
    "む": [("むし", "Insect"), ("むら", "Village"), ("むすこ", "Son"), ("むすめ", "Daughter"), ("むり", "Impossible"), ("むかし", "Long ago"), ("むこう", "Over there/opposite"), ("むね", "Chest"), ("むずかしい", "Difficult"), ("むだ", "Waste")],
    "め": [("め", "Eye"), ("めがね", "Glasses"), ("めし", "Meal"), ("めずらしい", "Rare"), ("めいし", "Business card"), ("めだまやき", "Fried egg"), ("めんどう", "Troublesome"), ("めざまし", "Alarm clock"), ("めいわく", "Trouble/nuisance"), ("めろん", "Melon")],
    "も": [("もり", "Forest"), ("もんだい", "Problem"), ("もち", "Rice cake"), ("もも", "Peach"), ("もくようび", "Thursday"), ("もどる", "Return"), ("もつ", "Hold/possess"), ("もったいない", "What a waste"), ("もじ", "Character/letter"), ("もしも", "If")],
    "や": [("やま", "Mountain"), ("やさい", "Vegetable"), ("やすみ", "Rest/holiday"), ("やさしい", "Kind/easy"), ("やる", "Do"), ("やくそく", "Promise"), ("やきゅう", "Baseball"), ("やっぱり", "As expected"), ("やく", "Bake/role"), ("やね", "Roof")],
    "ゆ": [("ゆき", "Snow"), ("ゆめ", "Dream"), ("ゆび", "Finger"), ("ゆうがた", "Evening"), ("ゆうめい", "Famous"), ("ゆっくり", "Slowly"), ("ゆでる", "Boil"), ("ゆうびん", "Mail"), ("ゆか", "Floor"), ("ゆうき", "Courage")],
    "よ": [("よる", "Night"), ("よむ", "Read"), ("よてい", "Plan/schedule"), ("よわい", "Weak"), ("よこ", "Side"), ("よろこぶ", "Be pleased"), ("ようふく", "Western clothes"), ("ようい", "Preparation"), ("よい", "Good"), ("よっつ", "Four things")],
    "ら": [("らいねん", "Next year"), ("らーめん", "Ramen"), ("らく", "Easy/comfortable"), ("らっぱ", "Trumpet"), ("らんち", "Lunch"), ("らしんばん", "Compass"), ("らいおん", "Lion"), ("らくがき", "Doodle"), ("らせん", "Spiral"), ("らじお", "Radio")],
    "り": [("りんご", "Apple"), ("りょうり", "Cooking"), ("りゆう", "Reason"), ("りかい", "Understanding"), ("りそう", "Ideal"), ("りっぱ", "Splendid"), ("りよう", "Use"), ("りれきしょ", "Resume"), ("りす", "Squirrel"), ("りずむ", "Rhythm")],
    "る": [("るす", "Absence"), ("るーる", "Rule"), ("るーぷ", "Loop"), ("るーと", "Route"), ("るびー", "Ruby"), ("るすばん", "House-sitting"), ("るいじ", "Similarity"), ("るんるん", "Cheerful mood"), ("るあー", "Fishing lure"), ("るーきー", "Rookie")],
    "れ": [("れいぞうこ", "Refrigerator"), ("れきし", "History"), ("れんしゅう", "Practice"), ("れつ", "Line/queue"), ("れすとらん", "Restaurant"), ("れい", "Zero/example"), ("れんらく", "Contact"), ("れんあい", "Romance"), ("れいぎ", "Manners"), ("れもん", "Lemon")],
    "ろ": [("ろうか", "Hallway"), ("ろてんぶろ", "Open-air bath"), ("ろうそく", "Candle"), ("ろく", "Six"), ("ろじ", "Alley"), ("ろぼっと", "Robot"), ("ろんぶん", "Thesis"), ("ろまん", "Romance"), ("ろーる", "Roll"), ("ろじっく", "Logic")],
    "わ": [("わたし", "I/me"), ("わに", "Crocodile"), ("わらう", "Laugh"), ("わかる", "Understand"), ("わすれる", "Forget"), ("わるい", "Bad"), ("わしつ", "Japanese-style room"), ("わんこ", "Dog (casual)"), ("わごむ", "Rubber band"), ("わかめ", "Wakame seaweed")],
    "を": [("みずをのむ", "Drink water"), ("ほんをよむ", "Read a book"), ("てがみをかく", "Write a letter"), ("おんがくをきく", "Listen to music"), ("しゃしんをとる", "Take a photo"), ("でんわをかける", "Make a phone call"), ("へやをそうじする", "Clean a room"), ("えいがをみる", "Watch a movie"), ("ごはんをたべる", "Eat a meal"), ("くるまをうんてんする", "Drive a car")],
    "ん": [("ぱん", "Bread"), ("ほん", "Book"), ("りんご", "Apple"), ("せんせい", "Teacher"), ("にほん", "Japan"), ("しんぶん", "Newspaper"), ("でんしゃ", "Train"), ("えんぴつ", "Pencil"), ("かんじ", "Kanji"), ("てんき", "Weather")],
    "が": [("がっこう", "School"), ("がくせい", "Student"), ("がいこく", "Foreign country"), ("がぞう", "Image"), ("がんばる", "Do one's best"), ("がいど", "Guide"), ("がまん", "Endurance"), ("がいしゃ", "Company"), ("がす", "Gas"), ("がくしゅう", "Study/learning")],
    "ぎ": [("ぎんこう", "Bank"), ("ぎゅうにゅう", "Milk"), ("ぎじゅつ", "Technology"), ("ぎもん", "Question/doubt"), ("ぎりぎり", "Just barely"), ("ぎょうざ", "Gyoza"), ("ぎんいろ", "Silver color"), ("ぎゃく", "Reverse"), ("ぎしき", "Ceremony"), ("ぎたー", "Guitar")],
    "ぐ": [("ぐあい", "Condition"), ("ぐんて", "Gloves"), ("ぐるぐる", "Round and round"), ("ぐっすり", "Sound asleep"), ("ぐらす", "Glass"), ("ぐち", "Complaint"), ("ぐんかん", "Warship"), ("ぐらい", "About/approximately"), ("ぐうぜん", "By chance"), ("ぐみ", "Gummy candy")],
    "げ": [("げんき", "Healthy/energetic"), ("げつようび", "Monday"), ("げーむ", "Game"), ("げんいん", "Cause"), ("げんご", "Language"), ("げんかん", "Entrance"), ("げきじょう", "Theater"), ("げんじつ", "Reality"), ("げんざい", "Present/current"), ("げきから", "Very spicy")],
}

relationships = [
    (kana, word, meaning)
    for kana, entries in words_by_kana.items()
    for word, meaning in entries
]
