HIRAGANA_ENTRIES = [
    {"kana": "あ", "romaji": "a", "pronunciation": "ah"},
    {"kana": "い", "romaji": "i", "pronunciation": "ee"},
    {"kana": "う", "romaji": "u", "pronunciation": "oo"},
    {"kana": "え", "romaji": "e", "pronunciation": "eh"},
    {"kana": "お", "romaji": "o", "pronunciation": "oh"},
    {"kana": "か", "romaji": "ka", "pronunciation": "kah"},
    {"kana": "き", "romaji": "ki", "pronunciation": "kee"},
    {"kana": "く", "romaji": "ku", "pronunciation": "koo"},
    {"kana": "け", "romaji": "ke", "pronunciation": "keh"},
    {"kana": "こ", "romaji": "ko", "pronunciation": "koh"},
    {"kana": "さ", "romaji": "sa", "pronunciation": "sah"},
    {"kana": "し", "romaji": "shi", "pronunciation": "shee"},
    {"kana": "す", "romaji": "su", "pronunciation": "soo"},
    {"kana": "せ", "romaji": "se", "pronunciation": "seh"},
    {"kana": "そ", "romaji": "so", "pronunciation": "soh"},
    {"kana": "た", "romaji": "ta", "pronunciation": "tah"},
    {"kana": "ち", "romaji": "chi", "pronunciation": "chee"},
    {"kana": "つ", "romaji": "tsu", "pronunciation": "tsoo"},
    {"kana": "て", "romaji": "te", "pronunciation": "teh"},
    {"kana": "と", "romaji": "to", "pronunciation": "toh"},
    {"kana": "な", "romaji": "na", "pronunciation": "nah"},
    {"kana": "に", "romaji": "ni", "pronunciation": "nee"},
    {"kana": "ぬ", "romaji": "nu", "pronunciation": "noo"},
    {"kana": "ね", "romaji": "ne", "pronunciation": "neh"},
    {"kana": "の", "romaji": "no", "pronunciation": "noh"},
]
