"""Common Japanese particle examples for hiragana learning exercises."""

from __future__ import annotations


HIRAGANA_PARTICLE_EXAMPLES: list[dict[str, str]] = [
    {
        "hiragana": "わたしはがくせいです",
        "english": "I am a student",
        "particle": "は",
        "meaning": "topic marker",
    },
    {
        "hiragana": "これはほんです",
        "english": "This is a book",
        "particle": "は",
        "meaning": "topic marker",
    },
    {
        "hiragana": "きょうはあめです",
        "english": "Today is rainy",
        "particle": "は",
        "meaning": "topic marker",
    },
    {
        "hiragana": "にほんごはむずかしいです",
        "english": "Japanese is difficult",
        "particle": "は",
        "meaning": "topic marker",
    },
    {
        "hiragana": "ねこはかわいいです",
        "english": "Cats are cute",
        "particle": "は",
        "meaning": "topic marker",
    },
    {
        "hiragana": "だれがきましたか",
        "english": "Who came?",
        "particle": "が",
        "meaning": "subject marker",
    },
    {
        "hiragana": "ねこがいます",
        "english": "There is a cat",
        "particle": "が",
        "meaning": "subject marker",
    },
    {
        "hiragana": "あめがふっています",
        "english": "It is raining",
        "particle": "が",
        "meaning": "subject marker",
    },
    {
        "hiragana": "わたしがします",
        "english": "I will do it",
        "particle": "が",
        "meaning": "subject marker",
    },
    {
        "hiragana": "りんごがすきです",
        "english": "I like apples",
        "particle": "が",
        "meaning": "subject marker",
    },
    {
        "hiragana": "みずをのみます",
        "english": "Drink water",
        "particle": "を",
        "meaning": "direct object marker",
    },
    {
        "hiragana": "ほんをよみます",
        "english": "Read a book",
        "particle": "を",
        "meaning": "direct object marker",
    },
    {
        "hiragana": "おんがくをききます",
        "english": "Listen to music",
        "particle": "を",
        "meaning": "direct object marker",
    },
    {
        "hiragana": "てがみをかきます",
        "english": "Write a letter",
        "particle": "を",
        "meaning": "direct object marker",
    },
    {
        "hiragana": "ごはんをたべます",
        "english": "Eat a meal",
        "particle": "を",
        "meaning": "direct object marker",
    },
    {
        "hiragana": "ろくじにおきます",
        "english": "Wake up at six o'clock",
        "particle": "に",
        "meaning": "time at / destination to",
    },
    {
        "hiragana": "がっこうにいきます",
        "english": "Go to school",
        "particle": "に",
        "meaning": "destination to",
    },
    {
        "hiragana": "つくえのうえにほんがあります",
        "english": "There is a book on the desk",
        "particle": "に",
        "meaning": "location at",
    },
    {
        "hiragana": "ともだちにでんわします",
        "english": "Call a friend",
        "particle": "に",
        "meaning": "target to",
    },
    {
        "hiragana": "せんせいになりたいです",
        "english": "I want to become a teacher",
        "particle": "に",
        "meaning": "result of change into",
    },
    {
        "hiragana": "日本へ行く",
        "english": "Go to Japan",
        "particle": "へ",
        "meaning": "direction toward",
    },
    {
        "hiragana": "うちへかえります",
        "english": "Return home",
        "particle": "へ",
        "meaning": "direction toward",
    },
    {
        "hiragana": "みぎへまがってください",
        "english": "Please turn right",
        "particle": "へ",
        "meaning": "direction toward",
    },
    {
        "hiragana": "そらへとびます",
        "english": "Fly toward the sky",
        "particle": "へ",
        "meaning": "direction toward",
    },
    {
        "hiragana": "えきへあるきます",
        "english": "Walk toward the station",
        "particle": "へ",
        "meaning": "direction toward",
    },
    {
        "hiragana": "としょかんでべんきょうします",
        "english": "Study at the library",
        "particle": "で",
        "meaning": "location of an action",
    },
    {
        "hiragana": "はしでたべます",
        "english": "Eat with chopsticks",
        "particle": "で",
        "meaning": "means or method",
    },
    {
        "hiragana": "バスでいきます",
        "english": "Go by bus",
        "particle": "で",
        "meaning": "means or method",
    },
    {
        "hiragana": "にほんごでかきます",
        "english": "Write in Japanese",
        "particle": "で",
        "meaning": "language used",
    },
    {
        "hiragana": "みんなでたべましょう",
        "english": "Let's eat together",
        "particle": "で",
        "meaning": "group participating",
    },
    {
        "hiragana": "ともだちとあそびます",
        "english": "Play with a friend",
        "particle": "と",
        "meaning": "together with",
    },
    {
        "hiragana": "パンとたまごをたべます",
        "english": "Eat bread and eggs",
        "particle": "と",
        "meaning": "and / listing",
    },
    {
        "hiragana": "せんせいとがくせいです",
        "english": "A teacher and a student",
        "particle": "と",
        "meaning": "and / listing",
    },
    {
        "hiragana": "ちちとでかけます",
        "english": "Go out with my father",
        "particle": "と",
        "meaning": "together with",
    },
    {
        "hiragana": "だれといきますか",
        "english": "Who are you going with?",
        "particle": "と",
        "meaning": "together with",
    },
    {
        "hiragana": "わたしもいきます",
        "english": "I will go too",
        "particle": "も",
        "meaning": "also / too",
    },
    {
        "hiragana": "これもください",
        "english": "This one too, please",
        "particle": "も",
        "meaning": "also / too",
    },
    {
        "hiragana": "だれもいません",
        "english": "There is nobody",
        "particle": "も",
        "meaning": "any / nobody with a negative",
    },
    {
        "hiragana": "いちどもありません",
        "english": "Not even once",
        "particle": "も",
        "meaning": "even",
    },
    {
        "hiragana": "にほんごもえいごもはなせます",
        "english": "I can speak both Japanese and English",
        "particle": "も",
        "meaning": "both / also",
    },
    {
        "hiragana": "わたしのほんです",
        "english": "It is my book",
        "particle": "の",
        "meaning": "possession or association",
    },
    {
        "hiragana": "にほんのたべもの",
        "english": "Japanese food",
        "particle": "の",
        "meaning": "description or origin",
    },
    {
        "hiragana": "えきのちかくです",
        "english": "It is near the station",
        "particle": "の",
        "meaning": "location association",
    },
    {
        "hiragana": "これはだれのかさですか",
        "english": "Whose umbrella is this?",
        "particle": "の",
        "meaning": "possession",
    },
    {
        "hiragana": "あかいのをください",
        "english": "Please give me the red one",
        "particle": "の",
        "meaning": "nominalizer / one",
    },
    {
        "hiragana": "がっこうからかえります",
        "english": "Return from school",
        "particle": "から",
        "meaning": "starting point from",
    },
    {
        "hiragana": "ともだちからてがみがきました",
        "english": "A letter came from a friend",
        "particle": "から",
        "meaning": "source from",
    },
    {
        "hiragana": "ここからはじめます",
        "english": "Start from here",
        "particle": "から",
        "meaning": "starting point from",
    },
    {
        "hiragana": "しちじからしごとです",
        "english": "Work starts at seven",
        "particle": "から",
        "meaning": "starting time from",
    },
    {
        "hiragana": "せんせいからならいました",
        "english": "I learned from the teacher",
        "particle": "から",
        "meaning": "source from",
    },
    {
        "hiragana": "ごごごじまでべんきょうします",
        "english": "Study until five p.m.",
        "particle": "まで",
        "meaning": "endpoint until",
    },
    {
        "hiragana": "えきまであるきます",
        "english": "Walk as far as the station",
        "particle": "まで",
        "meaning": "endpoint until",
    },
    {
        "hiragana": "きょうまでです",
        "english": "It is until today",
        "particle": "まで",
        "meaning": "deadline until",
    },
    {
        "hiragana": "よるまでまちます",
        "english": "Wait until evening",
        "particle": "まで",
        "meaning": "endpoint until",
    },
    {
        "hiragana": "ここまでよんでください",
        "english": "Please read up to here",
        "particle": "まで",
        "meaning": "limit up to",
    },
    {
        "hiragana": "りんごやみかんをかいます",
        "english": "Buy apples, oranges, and so on",
        "particle": "や",
        "meaning": "non-exhaustive listing",
    },
    {
        "hiragana": "ほんやノートがあります",
        "english": "There are books, notebooks, and so on",
        "particle": "や",
        "meaning": "non-exhaustive listing",
    },
    {
        "hiragana": "つくえやいすをつくります",
        "english": "Make desks, chairs, and so on",
        "particle": "や",
        "meaning": "non-exhaustive listing",
    },
    {
        "hiragana": "スーパーやコンビニへいきます",
        "english": "Go to supermarkets, convenience stores, and so on",
        "particle": "や",
        "meaning": "non-exhaustive listing",
    },
    {
        "hiragana": "えんぴつやペンでかきます",
        "english": "Write with pencils, pens, and so on",
        "particle": "や",
        "meaning": "non-exhaustive listing",
    },
    {
        "hiragana": "これよりおおきいです",
        "english": "It is bigger than this",
        "particle": "より",
        "meaning": "comparison than",
    },
    {
        "hiragana": "きのうよりさむいです",
        "english": "It is colder than yesterday",
        "particle": "より",
        "meaning": "comparison than",
    },
    {
        "hiragana": "でんしゃよりバスがやすいです",
        "english": "The bus is cheaper than the train",
        "particle": "より",
        "meaning": "comparison than",
    },
    {
        "hiragana": "おちゃよりコーヒーがすきです",
        "english": "I like coffee more than tea",
        "particle": "より",
        "meaning": "comparison than",
    },
    {
        "hiragana": "あるくよりはやいです",
        "english": "It is faster than walking",
        "particle": "より",
        "meaning": "comparison than",
    },
    {
        "hiragana": "いいてんきですね",
        "english": "Nice weather, isn't it?",
        "particle": "ね",
        "meaning": "seeking agreement",
    },
    {
        "hiragana": "かわいいですね",
        "english": "It is cute, isn't it?",
        "particle": "ね",
        "meaning": "seeking agreement",
    },
    {
        "hiragana": "あしたですね",
        "english": "It is tomorrow, right?",
        "particle": "ね",
        "meaning": "seeking agreement",
    },
    {
        "hiragana": "たいへんですね",
        "english": "That is difficult, isn't it?",
        "particle": "ね",
        "meaning": "empathy or agreement",
    },
    {
        "hiragana": "またあいましょうね",
        "english": "Let's meet again, okay?",
        "particle": "ね",
        "meaning": "soft emphasis",
    },
    {
        "hiragana": "これはほんですよ",
        "english": "This is a book, you know",
        "particle": "よ",
        "meaning": "giving information",
    },
    {
        "hiragana": "あぶないですよ",
        "english": "It is dangerous",
        "particle": "よ",
        "meaning": "warning or emphasis",
    },
    {
        "hiragana": "おいしいですよ",
        "english": "It is delicious",
        "particle": "よ",
        "meaning": "assertion or emphasis",
    },
    {
        "hiragana": "ここですよ",
        "english": "It is here",
        "particle": "よ",
        "meaning": "giving information",
    },
    {
        "hiragana": "だいじょうぶですよ",
        "english": "It is all right",
        "particle": "よ",
        "meaning": "reassurance or emphasis",
    },
    {
        "hiragana": "これはなんですか",
        "english": "What is this?",
        "particle": "か",
        "meaning": "question marker",
    },
    {
        "hiragana": "あしたいきますか",
        "english": "Will you go tomorrow?",
        "particle": "か",
        "meaning": "question marker",
    },
    {
        "hiragana": "どこですか",
        "english": "Where is it?",
        "particle": "か",
        "meaning": "question marker",
    },
    {
        "hiragana": "いくらですか",
        "english": "How much is it?",
        "particle": "か",
        "meaning": "question marker",
    },
    {
        "hiragana": "だれかいますか",
        "english": "Is anyone there?",
        "particle": "か",
        "meaning": "question or someone/anyone",
    },
    {
        "hiragana": "ひとつだけください",
        "english": "Please give me just one",
        "particle": "だけ",
        "meaning": "only / just",
    },
    {
        "hiragana": "きょうだけやすみます",
        "english": "I will rest only today",
        "particle": "だけ",
        "meaning": "only / just",
    },
    {
        "hiragana": "これだけたべます",
        "english": "I will eat only this much",
        "particle": "だけ",
        "meaning": "only / just",
    },
    {
        "hiragana": "にほんごだけはなせます",
        "english": "I can speak only Japanese",
        "particle": "だけ",
        "meaning": "only",
    },
    {
        "hiragana": "すこしだけわかります",
        "english": "I understand just a little",
        "particle": "だけ",
        "meaning": "only / just",
    },
    {
        "hiragana": "みずしかありません",
        "english": "There is nothing but water",
        "particle": "しか",
        "meaning": "nothing but with negative",
    },
    {
        "hiragana": "ひとつしかありません",
        "english": "There is only one",
        "particle": "しか",
        "meaning": "only with negative",
    },
    {
        "hiragana": "にほんごしかはなせません",
        "english": "I can speak only Japanese",
        "particle": "しか",
        "meaning": "only with negative",
    },
    {
        "hiragana": "きょうしかいけません",
        "english": "I can go only today",
        "particle": "しか",
        "meaning": "only with negative",
    },
    {
        "hiragana": "こどもしかいません",
        "english": "There are only children",
        "particle": "しか",
        "meaning": "only with negative",
    },
    {
        "hiragana": "さんじかんくらいねました",
        "english": "I slept for about three hours",
        "particle": "くらい",
        "meaning": "approximation about",
    },
    {
        "hiragana": "ごふんくらいまってください",
        "english": "Please wait about five minutes",
        "particle": "くらい",
        "meaning": "approximation about",
    },
    {
        "hiragana": "ひとりくらいきます",
        "english": "About one person will come",
        "particle": "くらい",
        "meaning": "approximation about",
    },
    {
        "hiragana": "これくらいのサイズです",
        "english": "It is about this size",
        "particle": "くらい",
        "meaning": "approximation about",
    },
    {
        "hiragana": "あるいていけるくらいちかいです",
        "english": "It is close enough to walk to",
        "particle": "くらい",
        "meaning": "degree or extent",
    },
    {
        "hiragana": "ひとりずつはいってください",
        "english": "Please enter one person at a time",
        "particle": "ずつ",
        "meaning": "each / at a time",
    },
    {
        "hiragana": "ふたつずつください",
        "english": "Please give me two each",
        "particle": "ずつ",
        "meaning": "each",
    },
    {
        "hiragana": "まいにちすこしずつべんきょうします",
        "english": "I study a little each day",
        "particle": "ずつ",
        "meaning": "little by little",
    },
    {
        "hiragana": "ひとつずつわけます",
        "english": "Divide them one each",
        "particle": "ずつ",
        "meaning": "each",
    },
    {
        "hiragana": "さんにんずつすわります",
        "english": "Sit three people at a time",
        "particle": "ずつ",
        "meaning": "each / at a time",
    },
]


def get_particle_exercises() -> list[dict[str, str]]:
    """Return a copy of the particle examples for exercise use."""
    return [dict(example) for example in HIRAGANA_PARTICLE_EXAMPLES]
