words_by_kana = {
    "ア": [("アニメ", "Anime"), ("アイス", "Ice cream"), ("アメリカ", "America"), ("アパート", "Apartment"), ("アプリ", "App"), ("アクション", "Action"), ("アカウント", "Account"), ("アクセス", "Access"), ("アナログ", "Analog"), ("アンテナ", "Antenna")],
    "イ": [("イカ", "Squid"), ("イヌ", "Dog"), ("イス", "Chair"), ("イタリア", "Italy"), ("イメージ", "Image"), ("インストール", "Install"), ("イノベーション", "Innovation"), ("イベント", "Event"), ("インデックス", "Index"), ("インク", "Ink")],
    "ウ": [("ウマ", "Horse"), ("ウミ", "Sea"), ("ウェブ", "Web"), ("ウイルス", "Virus"), ("ウォーター", "Water"), ("ウェア", "Wear"), ("ウィンドウ", "Window"), ("ウェーブ", "Wave"), ("ウォーク", "Walk"), ("ウクライナ", "Ukraine")],
    "エ": [("エネルギー", "Energy"), ("エアコン", "Air conditioner"), ("エンジン", "Engine"), ("エリア", "Area"), ("エレベーター", "Elevator"), ("エラー", "Error"), ("エッジ", "Edge"), ("エスカレーター", "Escalator"), ("エコ", "Eco"), ("エディション", "Edition")],
    "オ": [("オフィス", "Office"), ("オーケストラ", "Orchestra"), ("オーストラリア", "Australia"), ("オプション", "Option"), ("オンライン", "Online"), ("オブジェクト", "Object"), ("オペレーション", "Operation"), ("オレンジ", "Orange"), ("オート", "Auto"), ("オリジナル", "Original")],
    "カ": [("カメラ", "Camera"), ("カレンダー", "Calendar"), ("スカート", "Skirt"), ("カード", "Card"), ("カタログ", "Catalog"), ("カフェ", "Cafe"), ("カプセル", "Capsule"), ("カンパニー", "Company"), ("メカニック", "Mechanic"), ("アメリカ", "America")],
    "キ": [("キーボード", "Keyboard"), ("キャンプ", "Camp"), ("スキー", "Ski"), ("ケーキ", "Cake"), ("キッチン", "Kitchen"), ("ミキサー", "Mixer"), ("ドキュメント", "Document"), ("キーワード", "Keyword"), ("キリン", "Giraffe"), ("キャリア", "Career")],
    "ク": [("クラス", "Class"), ("クイズ", "Quiz"), ("クリーム", "Cream"), ("クッキー", "Cookie"), ("クレジット", "Credit"), ("バック", "Bag"), ("クロック", "Clock"), ("タクシー", "Taxi"), ("テクノ", "Techno"), ("アタック", "Attack")],
    "ケ": [("ケーキ", "Cake"), ("ケーブル", "Cable"), ("ケア", "Care"), ("ケチャップ", "Ketchup"), ("マーケット", "Market"), ("チケット", "Ticket"), ("バスケット", "Basket"), ("アンケート", "Survey"), ("ケント", "Kent"), ("オーケー", "OK")],
    "コ": [("コーヒー", "Coffee"), ("コンピュータ", "Computer"), ("コート", "Coat"), ("コイン", "Coin"), ("コンセント", "Outlet"), ("コンサート", "Concert"), ("コメント", "Comment"), ("レコード", "Record"), ("コレクション", "Collection"), ("アイコン", "Icon")],
    "サ": [("サラダ", "Salad"), ("サッカー", "Soccer"), ("サービス", "Service"), ("サンプル", "Sample"), ("サンド", "Sandwich"), ("サイズ", "Size"), ("サイン", "Sign"), ("ミキサー", "Mixer"), ("リサーチ", "Research"), ("センサー", "Sensor")],
    "シ": [("システム", "System"), ("シンプル", "Simple"), ("シーン", "Scene"), ("シェア", "Share"), ("シナリオ", "Scenario"), ("シルク", "Silk"), ("シール", "Seal"), ("シフト", "Shift"), ("ファッション", "Fashion"), ("レシピ", "Recipe")],
    "ス": [("スープ", "Soup"), ("スマホ", "Smartphone"), ("スペース", "Space"), ("スケジュール", "Schedule"), ("スイッチ", "Switch"), ("スカート", "Skirt"), ("バス", "Bus"), ("マスク", "Mask"), ("ディスク", "Disk"), ("ニュース", "News")],
    "セ": [("セール", "Sale"), ("センサー", "Sensor"), ("セミナー", "Seminar"), ("セット", "Set"), ("セレクト", "Select"), ("セーフ", "Safe"), ("アクセス", "Access"), ("メッセージ", "Message"), ("ライセンス", "License"), ("コンセプト", "Concept")],
    "ソ": [("ソファ", "Sofa"), ("ソース", "Sauce"), ("ソフト", "Software"), ("ソング", "Song"), ("ソケット", "Socket"), ("ソリューション", "Solution"), ("ソロ", "Solo"), ("パソコン", "PC"), ("マラソン", "Marathon"), ("コンソール", "Console")],
    "タ": [("タクシー", "Taxi"), ("タオル", "Towel"), ("タイトル", "Title"), ("タブレット", "Tablet"), ("タスク", "Task"), ("スタート", "Start"), ("センター", "Center"), ("データ", "Data"), ("ギター", "Guitar"), ("ドクター", "Doctor")],
    "チ": [("チーズ", "Cheese"), ("チーム", "Team"), ("チケット", "Ticket"), ("チョコ", "Chocolate"), ("キッチン", "Kitchen"), ("ランチ", "Lunch"), ("マッチ", "Match"), ("ストレッチ", "Stretch"), ("チャンス", "Chance"), ("チャート", "Chart")],
    "ツ": [("ツアー", "Tour"), ("ツール", "Tool"), ("スーツ", "Suit"), ("シャツ", "Shirt"), ("テスト", "Test"), ("グッズ", "Goods"), ("キッズ", "Kids"), ("ノーツ", "Notes"), ("スポーツ", "Sports"), ("ツイート", "Tweet")],
    "テ": [("テレビ", "TV"), ("テーブル", "Table"), ("テスト", "Test"), ("テキスト", "Text"), ("ホテル", "Hotel"), ("システム", "System"), ("ステージ", "Stage"), ("テンプレート", "Template"), ("アイテム", "Item"), ("コンテナ", "Container")],
    "ト": [("トマト", "Tomato"), ("トースト", "Toast"), ("トラック", "Truck"), ("トレーニング", "Training"), ("トンネル", "Tunnel"), ("ノート", "Notebook"), ("サイト", "Site"), ("ストーリー", "Story"), ("ヒント", "Hint"), ("アウト", "Out")],
    "ナ": [("ナイフ", "Knife"), ("ナース", "Nurse"), ("ナビ", "Navigation"), ("ナンバー", "Number"), ("ナポリ", "Naples"), ("バナナ", "Banana"), ("マナー", "Manner"), ("シナリオ", "Scenario"), ("サウナ", "Sauna"), ("ナチュラル", "Natural")],
    "ニ": [("ニュース", "News"), ("ニット", "Knit"), ("ニンジン", "Carrot"), ("ニックネーム", "Nickname"), ("ニーズ", "Needs"), ("ユニット", "Unit"), ("テニス", "Tennis"), ("パニック", "Panic"), ("エンジニア", "Engineer"), ("クリニック", "Clinic")],
    "ヌ": [("ヌードル", "Noodles"), ("ヌーボー", "Nouveau"), ("ヌガー", "Nougat"), ("カヌー", "Canoe"), ("メニュー", "Menu"), ("アンヌ", "Anne"), ("イヌ", "Dog"), ("ヌメリ", "Slime"), ("ヌード", "Nude"), ("ヌンス", "Nuns")],
    "ネ": [("ネット", "Net"), ("ネクタイ", "Necktie"), ("ネイル", "Nail"), ("ネーム", "Name"), ("ネガ", "Negative"), ("ネイビー", "Navy"), ("パネル", "Panel"), ("マヨネーズ", "Mayonnaise"), ("エネルギー", "Energy"), ("ルネサンス", "Renaissance")],
    "ノ": [("ノート", "Notebook"), ("ノイズ", "Noise"), ("ノルマ", "Quota"), ("ノック", "Knock"), ("ノベル", "Novel"), ("ノンアル", "Non-alcoholic"), ("ピアノ", "Piano"), ("シナモン", "Cinnamon"), ("テクノ", "Techno"), ("カジノ", "Casino")],
    "ハ": [("ハンバーガー", "Hamburger"), ("ハード", "Hard"), ("ハサミ", "Scissors"), ("ハイキング", "Hiking"), ("ハンドル", "Handle"), ("ハート", "Heart"), ("リハーサル", "Rehearsal"), ("チャーハン", "Fried rice"), ("バッハ", "Bach"), ("ハイブリッド", "Hybrid")],
    "ヒ": [("ヒーロー", "Hero"), ("ヒント", "Hint"), ("ヒーター", "Heater"), ("ヒット", "Hit"), ("ヒューマン", "Human"), ("コーヒー", "Coffee"), ("サヒール", "Sahil"), ("ヒップ", "Hip"), ("ヒマラヤ", "Himalaya"), ("ヒストリー", "History")],
    "フ": [("フルーツ", "Fruit"), ("フライ", "Fry"), ("フリー", "Free"), ("フロア", "Floor"), ("フット", "Foot"), ("ソファ", "Sofa"), ("グラフ", "Graph"), ("ライフ", "Life"), ("オフライン", "Offline"), ("フレーム", "Frame")],
    "ヘ": [("ヘア", "Hair"), ("ヘルプ", "Help"), ("ヘッド", "Head"), ("ヘリ", "Helicopter"), ("ヘビー", "Heavy"), ("カフェ", "Cafe"), ("ページ", "Page"), ("シェア", "Share"), ("ヘルシー", "Healthy"), ("ヘッダー", "Header")],
    "ホ": [("ホテル", "Hotel"), ("ホーム", "Home"), ("ホール", "Hall"), ("ホット", "Hot"), ("ホワイト", "White"), ("スマホ", "Smartphone"), ("イヤホン", "Earphones"), ("ホビー", "Hobby"), ("ホスト", "Host"), ("ホース", "Hose")],
    "マ": [("マイク", "Mic"), ("マップ", "Map"), ("マスク", "Mask"), ("マナー", "Manner"), ("マシン", "Machine"), ("テーマ", "Theme"), ("ドラマ", "Drama"), ("タイマー", "Timer"), ("サマー", "Summer"), ("マネージャー", "Manager")],
    "ミ": [("ミルク", "Milk"), ("ミラー", "Mirror"), ("ミニ", "Mini"), ("ミーティング", "Meeting"), ("ミックス", "Mix"), ("セミナー", "Seminar"), ("ビタミン", "Vitamin"), ("ファミリー", "Family"), ("ミサイル", "Missile"), ("ミュージック", "Music")],
    "ム": [("ムード", "Mood"), ("ムービー", "Movie"), ("ムース", "Mousse"), ("ムギ", "Wheat"), ("ゲーム", "Game"), ("チーム", "Team"), ("ホーム", "Home"), ("カスタム", "Custom"), ("アルバム", "Album"), ("リズム", "Rhythm")],
    "メ": [("メモ", "Memo"), ("メール", "Mail"), ("メニュー", "Menu"), ("メガネ", "Glasses"), ("メロン", "Melon"), ("コメント", "Comment"), ("カメラ", "Camera"), ("ドキュメント", "Document"), ("イメージ", "Image"), ("メンバー", "Member")],
    "モ": [("モデル", "Model"), ("モーター", "Motor"), ("モニター", "Monitor"), ("モバイル", "Mobile"), ("メモ", "Memo"), ("キモノ", "Kimono"), ("リモート", "Remote"), ("モジュール", "Module"), ("モノクロ", "Monochrome"), ("モチベーション", "Motivation")],
    "ヤ": [("ヤード", "Yard"), ("ヤシ", "Palm tree"), ("ヤング", "Young"), ("ダイヤ", "Diamond"), ("タイヤ", "Tire"), ("イヤホン", "Earphones"), ("ヘア", "Hair"), ("ロイヤル", "Royal"), ("ヤマト", "Yamato"), ("ヤフー", "Yahoo")],
    "ユ": [("ユニフォーム", "Uniform"), ("ユーザー", "User"), ("ユーモア", "Humor"), ("ユニット", "Unit"), ("ユニーク", "Unique"), ("ミュージック", "Music"), ("メニュー", "Menu"), ("キューブ", "Cube"), ("ユーロ", "Euro"), ("ユタ", "Utah")],
    "ヨ": [("ヨット", "Yacht"), ("ヨーグルト", "Yogurt"), ("ヨーロッパ", "Europe"), ("ヨガ", "Yoga"), ("ヨドバシ", "Yodobashi"), ("キヨスク", "Kiosk"), ("サヨナラ", "Goodbye"), ("ヨコ", "Side"), ("バイオ", "Bio"), ("トヨタ", "Toyota")],
    "ラ": [("ラーメン", "Ramen"), ("ラジオ", "Radio"), ("ライト", "Light"), ("ラベル", "Label"), ("ラウンジ", "Lounge"), ("カメラ", "Camera"), ("サラダ", "Salad"), ("プラグ", "Plug"), ("トラベル", "Travel"), ("ラッキー", "Lucky")],
    "リ": [("リスト", "List"), ("リンク", "Link"), ("リーダー", "Leader"), ("リモコン", "Remote control"), ("リズム", "Rhythm"), ("カロリー", "Calorie"), ("アプリ", "App"), ("メモリー", "Memory"), ("リサーチ", "Research"), ("リピート", "Repeat")],
    "ル": [("ルール", "Rule"), ("ルート", "Route"), ("ルーム", "Room"), ("ルビー", "Ruby"), ("ループ", "Loop"), ("ホテル", "Hotel"), ("メール", "Mail"), ("サークル", "Circle"), ("シンプル", "Simple"), ("ツール", "Tool")],
    "レ": [("レストラン", "Restaurant"), ("レベル", "Level"), ("レコード", "Record"), ("レシピ", "Recipe"), ("レッスン", "Lesson"), ("トレーニング", "Training"), ("フレーム", "Frame"), ("プレゼント", "Present"), ("エレベーター", "Elevator"), ("ディレクトリ", "Directory")],
    "ロ": [("ロボット", "Robot"), ("ロケット", "Rocket"), ("ロビー", "Lobby"), ("ロジック", "Logic"), ("ロング", "Long"), ("プロジェクト", "Project"), ("カロリー", "Calorie"), ("サラリーマン", "Office worker"), ("ローマ", "Rome"), ("メトロ", "Metro")],
    "ワ": [("ワイン", "Wine"), ("ワード", "Word"), ("ワクチン", "Vaccine"), ("ワンピース", "One-piece dress"), ("ワイヤー", "Wire"), ("シャワー", "Shower"), ("フラワー", "Flower"), ("パワー", "Power"), ("ワーク", "Work"), ("ワールド", "World")],
    "ヲ": [("ヲタク", "Otaku (archaic spelling)"), ("ヲルゴール", "Music box (archaic spelling)"), ("ヲレンジ", "Orange (archaic spelling)"), ("ヲペラ", "Opera (archaic spelling)"), ("ヲフィス", "Office (archaic spelling)"), ("ヲンライン", "Online (archaic spelling)"), ("ヲート", "Auto (archaic spelling)"), ("ヲアシス", "Oasis (archaic spelling)"), ("ヲリジナル", "Original (archaic spelling)"), ("ヲープン", "Open (archaic spelling)")],
    "ン": [("パン", "Bread"), ("エンジン", "Engine"), ("インク", "Ink"), ("オンライン", "Online"), ("コンピュータ", "Computer"), ("キャンプ", "Camp"), ("サンド", "Sandwich"), ("シンプル", "Simple"), ("ランチ", "Lunch"), ("メンバー", "Member")],
}

relationships = [
    (kana, word, meaning)
    for kana, entries in words_by_kana.items()
    for word, meaning in entries
]
