"""Household object vocabulary data for Japanese learners."""


HOUSEHOLD_OBJECTS = [
    {
        "word": "テーブル",
        "english_word": "table",
        "sentence": "家族とテーブルで晩ご飯を食べます。",
        "english_sentence": "I eat dinner at the table with my family.",
        "breakdown": [
            {"text": "家族と", "meaning": "with my family", "function": "companion phrase"},
            {"text": "テーブルで", "meaning": "at the table", "function": "location phrase"},
            {"text": "晩ご飯を", "meaning": "dinner", "function": "object"},
            {"text": "食べます", "meaning": "eat", "function": "polite verb"},
        ],
    },
    {
        "word": "いす",
        "english_word": "chair",
        "sentence": "このいすは長く座っても疲れません。",
        "english_sentence": "I do not get tired even after sitting in this chair for a long time.",
        "breakdown": [
            {"text": "この", "meaning": "this", "function": "determiner"},
            {"text": "いすは", "meaning": "chair", "function": "topic"},
            {"text": "長く", "meaning": "for a long time", "function": "adverb"},
            {"text": "座っても", "meaning": "even after sitting", "function": "concessive phrase"},
            {"text": "疲れません", "meaning": "do not get tired", "function": "polite negative verb"},
        ],
    },
    {
        "word": "つくえ",
        "english_word": "desk",
        "sentence": "つくえの上にノートパソコンを置きました。",
        "english_sentence": "I put my laptop on the desk.",
        "breakdown": [
            {"text": "つくえの上に", "meaning": "on the desk", "function": "destination phrase"},
            {"text": "ノートパソコンを", "meaning": "laptop", "function": "object"},
            {"text": "置きました", "meaning": "put", "function": "polite past verb"},
        ],
    },
    {
        "word": "ベッド",
        "english_word": "bed",
        "sentence": "疲れていたので、ベッドですぐ寝ました。",
        "english_sentence": "I was tired, so I fell asleep in bed right away.",
        "breakdown": [
            {"text": "疲れていたので", "meaning": "because I was tired", "function": "reason clause"},
            {"text": "ベッドで", "meaning": "in bed", "function": "location phrase"},
            {"text": "すぐ", "meaning": "right away", "function": "adverb"},
            {"text": "寝ました", "meaning": "slept", "function": "polite past verb"},
        ],
    },
    {
        "word": "まくら",
        "english_word": "pillow",
        "sentence": "旅行にまくらを持っていきます。",
        "english_sentence": "I take my pillow with me when I travel.",
        "breakdown": [
            {"text": "旅行に", "meaning": "on a trip", "function": "occasion phrase"},
            {"text": "まくらを", "meaning": "pillow", "function": "object"},
            {"text": "持っていきます", "meaning": "take along", "function": "polite verb"},
        ],
    },
    {
        "word": "かがみ",
        "english_word": "mirror",
        "sentence": "出かける前に、かがみで服を確認します。",
        "english_sentence": "I check my clothes in the mirror before going out.",
        "breakdown": [
            {"text": "出かける前に", "meaning": "before going out", "function": "time phrase"},
            {"text": "かがみで", "meaning": "in the mirror", "function": "means phrase"},
            {"text": "服を", "meaning": "clothes", "function": "object"},
            {"text": "確認します", "meaning": "check", "function": "polite verb"},
        ],
    },
    {
        "word": "れいぞうこ",
        "english_word": "refrigerator",
        "sentence": "買ってきた野菜をれいぞうこに入れました。",
        "english_sentence": "I put the vegetables I bought in the refrigerator.",
        "breakdown": [
            {"text": "買ってきた", "meaning": "bought and brought back", "function": "describes 野菜"},
            {"text": "野菜を", "meaning": "vegetables", "function": "object"},
            {"text": "れいぞうこに", "meaning": "into the refrigerator", "function": "destination phrase"},
            {"text": "入れました", "meaning": "put in", "function": "polite past verb"},
        ],
    },
    {
        "word": "せんたくき",
        "english_word": "washing machine",
        "sentence": "せんたくきが止まったので、電源を確認しました。",
        "english_sentence": "The washing machine stopped, so I checked the power.",
        "breakdown": [
            {"text": "せんたくきが", "meaning": "washing machine", "function": "subject"},
            {"text": "止まったので", "meaning": "because it stopped", "function": "reason clause"},
            {"text": "電源を", "meaning": "power", "function": "object"},
            {"text": "確認しました", "meaning": "checked", "function": "polite past verb"},
        ],
    },
    {
        "word": "そうじき",
        "english_word": "vacuum cleaner",
        "sentence": "私のそうじきが動かないので、床をほうきで掃きました。",
        "english_sentence": "My vacuum cleaner was not working, so I swept the floor with a broom.",
        "breakdown": [
            {"text": "私の", "meaning": "my", "function": "possessive phrase"},
            {"text": "そうじきが", "meaning": "vacuum cleaner", "function": "subject"},
            {"text": "動かないので", "meaning": "because it does not work", "function": "reason clause"},
            {"text": "床を", "meaning": "floor", "function": "object"},
            {"text": "ほうきで", "meaning": "with a broom", "function": "means phrase"},
            {"text": "掃きました", "meaning": "swept", "function": "polite past verb"},
        ],
    },
    {
        "word": "でんき",
        "english_word": "light",
        "sentence": "寝る前に、部屋のでんきを消してください。",
        "english_sentence": "Please turn off the room light before going to bed.",
        "breakdown": [
            {"text": "寝る前に", "meaning": "before going to bed", "function": "time phrase"},
            {"text": "部屋の", "meaning": "room's", "function": "possessive phrase"},
            {"text": "でんきを", "meaning": "light", "function": "object"},
            {"text": "消してください", "meaning": "please turn off", "function": "polite request"},
        ],
    },
    {
        "word": "ドア",
        "english_word": "door",
        "sentence": "出かける前に、ドアの鍵をかけました。",
        "english_sentence": "I locked the door before going out.",
        "breakdown": [
            {"text": "出かける前に", "meaning": "before going out", "function": "time phrase"},
            {"text": "ドアの", "meaning": "door's", "function": "possessive phrase"},
            {"text": "鍵を", "meaning": "lock", "function": "object"},
            {"text": "かけました", "meaning": "locked", "function": "polite past verb"},
        ],
    },
    {
        "word": "まど",
        "english_word": "window",
        "sentence": "朝、まどを開けて部屋の空気を入れ替えます。",
        "english_sentence": "In the morning, I open the window to air out the room.",
        "breakdown": [
            {"text": "朝", "meaning": "in the morning", "function": "time phrase"},
            {"text": "まどを", "meaning": "window", "function": "object"},
            {"text": "開けて", "meaning": "open and", "function": "て-form connector"},
            {"text": "部屋の空気を", "meaning": "the room's air", "function": "object"},
            {"text": "入れ替えます", "meaning": "change / air out", "function": "polite verb"},
        ],
    },
    {
        "word": "テレビ",
        "english_word": "television",
        "sentence": "夕食の後でテレビを見ます。",
        "english_sentence": "I watch television after dinner.",
        "breakdown": [
            {"text": "夕食の後で", "meaning": "after dinner", "function": "time phrase"},
            {"text": "テレビを", "meaning": "television", "function": "object"},
            {"text": "見ます", "meaning": "watch", "function": "polite verb"},
        ],
    },
    {
        "word": "リモコン",
        "english_word": "remote control",
        "sentence": "リモコンでテレビの音を小さくしました。",
        "english_sentence": "I turned down the television volume with the remote control.",
        "breakdown": [
            {"text": "リモコンで", "meaning": "with the remote control", "function": "means phrase"},
            {"text": "テレビの音を", "meaning": "the television's volume", "function": "object"},
            {"text": "小さくしました", "meaning": "made quieter", "function": "polite causative change"},
        ],
    },
    {
        "word": "とけい",
        "english_word": "clock",
        "sentence": "とけいを見て、急いで準備しました。",
        "english_sentence": "I looked at the clock and got ready quickly.",
        "breakdown": [
            {"text": "とけいを", "meaning": "clock", "function": "object"},
            {"text": "見て", "meaning": "looked at and", "function": "て-form connector"},
            {"text": "急いで", "meaning": "quickly / hurriedly", "function": "adverbial て-form"},
            {"text": "準備しました", "meaning": "prepared", "function": "polite past verb"},
        ],
    },
    {
        "word": "かさ",
        "english_word": "umbrella",
        "sentence": "雨が降りそうなので、かさを持っていきます。",
        "english_sentence": "It looks like it will rain, so I am taking an umbrella.",
        "breakdown": [
            {"text": "雨が", "meaning": "rain", "function": "subject"},
            {"text": "降りそうなので", "meaning": "because it looks like it will fall", "function": "reason clause"},
            {"text": "かさを", "meaning": "umbrella", "function": "object"},
            {"text": "持っていきます", "meaning": "take along", "function": "polite verb"},
        ],
    },
    {
        "word": "かばん",
        "english_word": "bag",
        "sentence": "かばんに教科書とノートを入れました。",
        "english_sentence": "I put the textbook and notebook in my bag.",
        "breakdown": [
            {"text": "かばんに", "meaning": "in the bag", "function": "destination phrase"},
            {"text": "教科書とノートを", "meaning": "textbook and notebook", "function": "compound object"},
            {"text": "入れました", "meaning": "put in", "function": "polite past verb"},
        ],
    },
    {
        "word": "さいふ",
        "english_word": "wallet",
        "sentence": "さいふを忘れたので、家に戻りました。",
        "english_sentence": "I forgot my wallet, so I returned home.",
        "breakdown": [
            {"text": "さいふを", "meaning": "wallet", "function": "object"},
            {"text": "忘れたので", "meaning": "because I forgot", "function": "reason clause"},
            {"text": "家に", "meaning": "home", "function": "destination"},
            {"text": "戻りました", "meaning": "returned", "function": "polite past verb"},
        ],
    },
    {
        "word": "かぎ",
        "english_word": "key",
        "sentence": "かぎをテーブルの上に置かないでください。",
        "english_sentence": "Please do not put the key on the table.",
        "breakdown": [
            {"text": "かぎを", "meaning": "key", "function": "object"},
            {"text": "テーブルの上に", "meaning": "on the table", "function": "destination phrase"},
            {"text": "置かないでください", "meaning": "please do not put", "function": "polite negative request"},
        ],
    },
    {
        "word": "スマートフォン",
        "english_word": "smartphone",
        "sentence": "スマートフォンで写真を撮りました。",
        "english_sentence": "I took a picture with my smartphone.",
        "breakdown": [
            {"text": "スマートフォンで", "meaning": "with a smartphone", "function": "means phrase"},
            {"text": "写真を", "meaning": "picture", "function": "object"},
            {"text": "撮りました", "meaning": "took", "function": "polite past verb"},
        ],
    },
    {
        "word": "パソコン",
        "english_word": "computer",
        "sentence": "毎晩パソコンでメールを確認します。",
        "english_sentence": "I check my email on the computer every night.",
        "breakdown": [
            {"text": "毎晩", "meaning": "every night", "function": "time phrase"},
            {"text": "パソコンで", "meaning": "on the computer", "function": "means phrase"},
            {"text": "メールを", "meaning": "email", "function": "object"},
            {"text": "確認します", "meaning": "check", "function": "polite verb"},
        ],
    },
    {
        "word": "タオル",
        "english_word": "towel",
        "sentence": "お風呂の後で、タオルで体を拭きます。",
        "english_sentence": "After a bath, I dry my body with a towel.",
        "breakdown": [
            {"text": "お風呂の後で", "meaning": "after a bath", "function": "time phrase"},
            {"text": "タオルで", "meaning": "with a towel", "function": "means phrase"},
            {"text": "体を", "meaning": "body", "function": "object"},
            {"text": "拭きます", "meaning": "wipe / dry", "function": "polite verb"},
        ],
    },
    {
        "word": "コップ",
        "english_word": "cup",
        "sentence": "コップに水を入れてください。",
        "english_sentence": "Please put water in the cup.",
        "breakdown": [
            {"text": "コップに", "meaning": "in the cup", "function": "destination phrase"},
            {"text": "水を", "meaning": "water", "function": "object"},
            {"text": "入れてください", "meaning": "please put in", "function": "polite request"},
        ],
    },
    {
        "word": "ごみ箱",
        "english_word": "trash can",
        "sentence": "ごみを分別して、ごみ箱に入れます。",
        "english_sentence": "I sort the trash and put it in the trash can.",
        "breakdown": [
            {"text": "ごみを", "meaning": "trash", "function": "object"},
            {"text": "分別して", "meaning": "sort and", "function": "て-form connector"},
            {"text": "ごみ箱に", "meaning": "in the trash can", "function": "destination phrase"},
            {"text": "入れます", "meaning": "put in", "function": "polite verb"},
        ],
    },
]
